### ISSUE TITLE
Problem with outputting decimals

### ISSUE THREAD

**Issue by mark3072** [pando-project/iotjs#1695]
Hi I had a great build of iotjs working on br_mips-2013.11 but when I switched to cs_mips-2014.05 I am now getting a strange error.

the code: 
console.log(10.1);

Now generates:
5
ICE: Assertion '!ecma_string_to_array_index (chars_p, string_p->u.utf8_string.size, &array_index)' failed at /home/mark3072/iotjs/deps/jerry/jerry-core/ecma/base/ecma-helpers-string.c(ecma_deref_ecma_string):919.

The underlying math functions work, it seems to be an issue with output of decimal numbers any ideas?

**Comment by LaszloLango** [comment]
It works for me on Ubuntu64bit. Might be a mips specific issue. What version of IoT.js are you using?
CC: @galpeter

**Comment by LaszloLango** [comment]
Closing due to long time inactivity.
