### ISSUE TITLE
jerryscript features

### ISSUE THREAD

**Issue by daeyeon** [pando-project/iotjs#1716]
In product, we may face cases where we can't depend on transpiling ES6. It seems necessary to builtin-support some features with consideration not to harm the main purpose of jerryscript. 

The followings are such a feature we feel to need while meeting a certain specification these days.

* Map, ~~Weakmap~~
* default parameters
* enhanced object literals
* class (on going in Jerryscript already)

Plus, we should start considering **thread-safe** jerryscript.

**Comment by yichoi** [comment]
Why don't you write these items at https://github.com/jerryscript-project/jerryscript/issues either?

**Comment by daeyeon** [comment]
I've issued https://github.com/jerryscript-project/jerryscript/issues/2433 for thread-safe jerryscript.

**Comment by daeyeon** [comment]
* thread-safe jerryscript: https://gist.github.com/rtakacs/3948e3294bb05fd9c74f1566f831c2ec

**Comment by LaszloLango** [comment]
@daeyeon all of these features are implemented. Can we close this issue?

**Comment by daeyeon** [comment]
@daeyeon Yes, and thanks for letting me know that.
